name: CI
on:
  push:
    branches:
    - main
    - test-m1
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  generate-linux-aarch64-native-launcher:
    runs-on: "macOS-m1"
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: VirtusLab/scala-cli-setup@7e6a0b2468fc28b94936417e4cad385e380ac735
        with:
          apps: ""
      - name: Generate native launcher and generate os packages
        run: .github/scripts/build-linux-aarch64.sh
      - uses: actions/upload-artifact@v3
        with:
          name: linux-aarch64-launchers
          path: artifacts/
          if-no-files-found: error
          retention-days: 2

  native-linux-aarch64-tests:
    needs: generate-linux-aarch64-native-launcher
    runs-on: "macOS-m1"
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: VirtusLab/scala-cli-setup@7e6a0b2468fc28b94936417e4cad385e380ac735
        with:
          apps: ""
      - uses: actions/download-artifact@v3
        with:
          name: linux-aarch64-launchers
          path: artifacts/
      - name: Native integration tests
        run: .github/scripts/test-linux-aarch64.sh
        env:
          UPDATE_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCALA_CLI_IT_FORCED_LAUNCHER_DIRECTORY: artifacts/
          SCALA_CLI_IT_GROUP: 1
          SCALA_CLI_SODIUM_JNI_ALLOW: false
